recipes-kernel: Remove linux-firmware backport 20200421
Linux firmware was upgrade to 20200817 in upstream,

https://git.openembedded.org/openembedded-core/commit/?h=dunfell&id=ecfc52630fb28ca2288c3319aea6a017d5878cc7

Fixes,

ERROR: Multiple versions of linux-firmware are due to be built (/srv/oe/build/conf/../../layers/meta-backports/core/recipes-kernel/linux-firmware/linux-firmware_20200421.bb /srv/oe/build/conf/../../layers/openembedded-core/meta/recipes-kernel/linux-firmware/linux-firmware_20200817.bb). Only one version of a given PN should be built in any given build. You likely need to set PREFERRED_VERSION_linux-firmware to select the correct version or don't depend on multiple versions.

Signed-off-by: Aníbal Limón <anibal.limon@linaro.org>
Change-Id: I27d0c939c90b5e4f3a830c986f70d48094667449